name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # Updated to a newer LTS version for better support

            - name: Install dependencies
              run: npm install

            - name: Run Lint
              run: npm lint

    docker-build:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-docker-buildx-${{ github.ref_name }}-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-docker-buildx-${{ github.ref_name }}-

            - name: Build and Run Tests with Docker Compose
              run: docker-compose -f docker-compose.yml run --rm app npm test
