name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20] # Add more versions like [18, 20] if multi-version testing is needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Automatically caches dependencies

      - name: Install dependencies
        run: npm i # Faster and more reliable than `npm install`

      - name: Run Lint
        run: npm run lint 

      - name: Run Jest
        run: npm run test